MeeseeksInc/MeeseeksInc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework import routers
from rest_framework.authtoken import views

from inventory import views as inventory_views



# Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'items', ItemViewSet)
# router.register(r'requests', RequestViewSet)
# router.register(r'disbursements', DisbursementViewSet)

urlpatterns = [
    url(r'^', include('inventory.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^customadmin/', include('custom_admin.urls')),
    url(r'^login/$', auth_views.login, {'template_name': 'inventory/login.html'}, name='login'), 
    url(r'^login/check_login/$', inventory_views.check_login, name='check_login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'inventory/logged_out.html'}, name='logout'),
    url(r'^login/check_OAuth_login/$', inventory_views.check_OAuth_login, name='check_OAuth_login'),
    url(r'^request_oauth/$', inventory_views.request_token, name='request_token'),
    url(r'^get_access_token/$', inventory_views.getAccessToken, name='get_access_token'), 
    # API URLS 
    url(r'^api-viewer/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', views.obtain_auth_token)
]

MeeseeksInc/custom_admin/urls.py
from dal import autocomplete
from django.conf.urls import url

from custom_admin.views import UserAutocomplete
import inventory

from . import views


#this app_name is important b/c Django needs to look through all the apps 
# and we need to differentiate
app_name = 'custom_admin'  
urlpatterns = [
    # the argument 'name' at the end of url() is IMPORTANT 
    # b/c we use it to load these urls later in the html files
    # this allows us to change the url of a page without changing it in the HTML files
     
    # if typed /, goes to following url
    # url(r'^$', views.AdminIndexView.as_view(), name='index'),

    url(r'^edit/loan/(?P<pk>[\w\-\ ]+)/$', views.LoanView.edit_loan, name='edit_loan'),
    url(r'^convert/loan/(?P<pk>[\w\-\ ]+)/$', views.LoanView.convert_loan, name='convert_loan'),
    url(r'^convert_with_assets/loan/(?P<pk>[\w\-\ ]+)/$', views.LoanView.convert_loan_with_assets, name='convert_loan_with_assets'),
    url(r'^checkIn/loan/(?P<pk>[\w\-\ ]+)/$', views.LoanView.check_in_loan, name='check_in_loan'),
    url(r'^checkin_with_assets/loan/(?P<pk>[\w\-\ ]+)/$', views.LoanView.check_in_loan_with_assets, name='check_in_loan_with_assets'),
    url(r'^request/accept/addcomment/(?P<pk>[\w\-\ ]+)/$', views.RequestsView.add_comment_to_request_accept, name='add_comment_to_request_accept'),
    url(r'^request/deny/addcomment/(?P<pk>[\w\-\ ]+)/$', views.RequestsView.add_comment_to_request_deny, name='add_comment_to_request_deny'),
    url(r'^request/asset_accept/(?P<pk>[\w\-\ ]+)/$', views.request_accept_with_assets, name='request_accept_with_assets'),
    url(r'^disburse/item$', views.DisbursementView.post_new_disburse, name='post_new_disburse'),
    url(r'^disburse/item/(?P<pk>[\w\-\ ]+)/$', views.DisbursementView.post_new_disburse_specific, name='post_specific_disburse'),
    url(r'^disburse/asset/(?P<pk>[\w\-\ ]+)/$', views.DisbursementView.post_new_disburse_asset, name='post_new_disburse_asset'),
    url(r'^deny/request/all$', views.RequestsView.deny_all_request, name='deny_all_requests'),
    url(r'^approve/request/all$', views.RequestsView.approve_all_requests, name='approve_all_requests'),
    url(r'^deny/request/(?P<pk>[\w\-\ ]+)/$', views.RequestsView.deny_request, name='deny_request'),
    url(r'^approve/request/(?P<pk>[\w\-\ ]+)/$', views.RequestsView.approve_request, name='approve_request'),
    url(r'^edit/item/module/(?P<pk>[\w\-\ ]+)/$', views.ItemView.edit_item_module, name='edit_item_module'),
    url(r'^create/item$', views.ItemView.create_new_item, name='create_new_item'),
    url(r'^delete/(?P<pk>[\w\-\ ]+)/$', views.ItemView.delete_item, name='delete_item'),
    url(r'^$', inventory.views.IndexView.as_view(), name='index'),
    
    url(r'^asset/edit/(?P<pk>[\w\-\ ]+)/$', views.AssetView.edit_asset, name='edit_asset'),
    url(r'^asset/delete/(?P<pk>[\w\-\ ]+)/$', views.AssetView.delete_asset, name='delete_asset'),
    url(r'^asset/delete/detail/(?P<pk>[\w\-\ ]+)/$', views.AssetView.delete_asset_from_detail, name='delete_asset_from_detail'),
    url(r'^add/assets/(?P<pk>[\w\-\ ]+)/$', views.AssetView.add_assets, name='add_assets'),
    
    url(r'^edit/tags/(?P<pk>[\w\-\ ]+)/$', views.TagView.add_tags_module, name='tags_module'),
    url(r'^delete/tag/(?P<pk>[\w\-\ ]+)/(?P<item>[\w\-\ ]+)/$', views.TagView.delete_tag, name='delete_tag'),
    
    url(r'^add_custom_field/$', views.CustomFieldView.as_view(), name='add_custom_field'),
    url(r'^delete_custom_field/$', views.CustomFieldView.delete_custom_field, name='delete_custom_field'),
    url(r'^modify_custom_field/$', views.CustomFieldView.modify_custom_field, name='modify_custom_field'),
    url(r'^modify_custom_field/(?P<pk>[\w\-\ ]+)/$', views.CustomFieldView.modify_custom_field_modal, name='modify_custom_field_modal'),
    
    url(r'^log$', views.LogView.as_view(), name='log'),
    url(r'^log_item$', views.LogView.log_item, name='log_item'),
    url(r'^destroy/asset/(?P<pk>[\w\-\ ]+)/$', views.LogView.log_asset, name='destroy_asset'),
    
    url(r'^edit/user_permission/(?P<pk>[\w\-\ ]+)/$', views.UserListView.edit_permission, name='edit_permission'),
    url(r'^users/$', views.UserListView.as_view(), name='user_page'),
    url(r'^userfield-autocomplete/$', views.UserAutocomplete.as_view(), name='userfield-autocomplete'),
    url(r'^registration/$', views.RegistrationView.as_view(), name = 'register_page'),
    
    url(r'^subscription/$', views.EmailView.subscribe, name='subscribe'),
    url(r'^edit_prepend/$', views.EmailView.change_email_prepend, name='change_email_prepend'),
    url(r'^send_email/$', views.EmailView.create_email, name='send_email'),
    url(r'delay_email/$', views.EmailView.delay_email, name='delay_email'),
    url(r'change_loan_email_body/$', views.EmailView.loan_reminder_body, name='change_loan_body'),
    url(r'delete_task_queue/$', views.EmailView.delete_task_queue, name='delete_task_queue'),
    
    url(r'^csv/guide/$',inventory.views.csv_guide_page,name='csv_help'),
    url(r'^upload/$', views.upload_page, name='upload_page'),
    url(r'^backfill/from/loan/(?P<pk>[\w\-\ ]+)/$', views.create_backfill_from_loan, name='backfill_from_loan'),
    url(r'^backfill/accept/addcomment/(?P<pk>[\w\-\ ]+)/$', views.add_comment_to_backfill_accept, name='add_comment_to_backfill_accept'),
    url(r'^backfill/deny/addcomment/(?P<pk>[\w\-\ ]+)/$', views.add_comment_to_backfill_deny, name='add_comment_to_backfill_deny'),
    url(r'^backfill/complete/addcomment/(?P<pk>[\w\-\ ]+)/$', views.add_comment_to_backfill_complete, name='add_comment_to_backfill_complete'),
    url(r'^backfill/complete/addcomment/asset/(?P<pk>[\w\-\ ]+)/$', views.add_comment_to_backfill_asset_complete, name='add_comment_to_backfill_complete_asset'),
    url(r'^backfill/fail/addcomment/(?P<pk>[\w\-\ ]+)/$', views.add_comment_to_backfill_fail, name='add_comment_to_backfill_fail'),
    url(r'^backfill/add/notes/(?P<pk>[\w\-\ ]+)/$', views.add_notes_to_backfill, name='add_notes_to_backfill'),
]

MeeseeksInc/inventory/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

import custom_admin.views
import inventory.api

from . import views


# this app_name is important b/c Django needs to look through all the apps 
# and we need to differentiate
app_name = 'inventory'  
urlpatterns = [
    url(r'^api/token/$', views.get_api_token, name='api_token'),
    # the argument 'name' at the end of url() is IMPORTANT 
    # b/c we use it to load these urls later in the html files
    # this allows us to change the url of a page without changing it in the HTML files
     
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^item/(?P<pk>[\w\-\ ]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^inventory_cart$', views.CartListView.as_view(), name='inventory_cart'),
    url(r'^inventory_cart/delete/(?P<pk>[\w\-\ ]+)/$', views.CartListView.delete_cart_instance, name='delete_cart_instance'),
    url(r'^post/request/(?P<pk>[\w\-\ ]+)/$', views.RequestDetailView.request_specific_item, name='request_specific_item'),
    url(r'^request_edit/(?P<pk>[\w\-\ ]+)/$', views.RequestDetailView.edit_request, name='request_edit'),
    url(r'^request_detail/(?P<pk>[\w\-\ ]+)/$', views.RequestDetailView.as_view(), name='request_detail'),
    url(r'^(?P<pk>[\w\-\ ]+)/cancel/$', views.RequestDetailView.cancel_request, name='request_cancel'),
    url(r'^item_detail/(?P<pk>[\w\-\ ]+)/cancel/$', views.RequestDetailView.cancel_request, name='item_detail_request_cancel'),
 #   url(r'^loan/detail/checkIn/loan/(?P<pk>[\w\-\ ]+)/$', custom_admin.views.check_in_loan, name='check_in_loan'), 
    url(r'^loan/detail/edit/loan/(?P<pk>[\w\-\ ]+)/$', custom_admin.views.LoanView.edit_loan, name='edit_loan'), 
    url(r'^loan/detail/(?P<pk>[\w\-\ ]+)/$', views.LoanDetailView.as_view(), name='loan_detail'),
    url(r'^asset/(?P<pk>[\w\-\ ]+)/$', views.AssetDetailView.as_view(), name='asset_detail'),
    ################################### API URLS #######################################
    url(r'^api/items/$', inventory.api.APIItemList.as_view(), name='api_item_list'),
    url(r'^api/items/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIItemDetail.as_view(), name='api_item_detail'),
    url(r'^api/requests/$', inventory.api.APIRequestList.as_view()),
    url(r'^api/requests/create/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIRequestThroughItem.as_view()),
#     url(r'^api/requests/multiple_create/(?P<item_list>[\w\-\ (\,)?]+)/$', inventory.api.APIMultipleRequests.as_view()),
    url(r'^api/requests/multiple_create/$', inventory.api.APIMultipleRequests.as_view()),
    url(r'^api/requests/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIRequestDetail.as_view()),
    url(r'^api/requests/approve/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIApproveRequest.as_view()),
    url(r'^api/requests/deny/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIDenyRequest.as_view()),
    url(r'^api/requests/approve_with_assets/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIApproveRequestWithAssets.as_view()),
    url(r'^api/disbursements/$', inventory.api.APIDisbursementList.as_view()),
    url(r'^api/disbursements/direct/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIDirectDisbursement.as_view()),
    url(r'^api/disbursements/direct/with/assets/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIDirectDisbursementWithAssets.as_view()),
    url(r'^api/users/$', inventory.api.APIUserList.as_view()),
    url(r'^api/users/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIUserDetail.as_view()),
    url(r'^api/custom/field/$', inventory.api.APICustomField.as_view()),
    url(r'^api/custom/field/modify/(?P<pk>[\w\-\ ]+)/$', inventory.api.APICustomFieldModify.as_view()),
    url(r'^api/asset/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIAsset.as_view()),
    url(r'^api/add/assets/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIAddAsset.as_view()),
    url(r'^api/tags/$', inventory.api.APITagList.as_view(), name='api_tag_list'),
    url(r'^api/logs/$', inventory.api.APILogList.as_view(), name='api_log_list'),
    url(r'^api/loan/checkin/(?P<pk>[\w\-\ ]+)/$', inventory.api.APILoanCheckIn.as_view(), name='api_loan_checkin'),
    url(r'^api/loan/checkin_with_assets/(?P<pk>[\w\-\ ]+)/$', inventory.api.APILoanCheckInWithAssets.as_view(), name='api_loan_checkin_with_assets'),
    url(r'^api/loan/convert/(?P<pk>[\w\-\ ]+)/$', inventory.api.APILoanConvert.as_view(), name='api_loan_convert'),
    url(r'^api/loan/convert_with_assets/(?P<pk>[\w\-\ ]+)/$', inventory.api.APILoanConvertWithAssets.as_view(), name='api_loan_convert_with_assets'),
    url(r'^api/loan/update/(?P<pk>[\w\-\ ]+)/$', inventory.api.APILoanUpdate.as_view(), name='api_loan_update'),
    url(r'^api/loan/$', inventory.api.APILoanList.as_view(), name='api_loan_list'),
    url(r'^api/guide/$', custom_admin.views.api_guide_page, name='api_guide'),
    url(r'^api/upload/$', inventory.api.ItemUpload.as_view(), name='upload'),
    url(r'^api/upload/asset/$', inventory.api.AssetUpload.as_view(), name='asset_upload'),    
    url(r'^api/subscribe/(?P<pk>[\w\-\ ]+)/$', inventory.api.APISubscriptionDetail.as_view(), name='subscribe'),
    url(r'^api/loan/email/body/$', inventory.api.APILoanEmailBody.as_view(), name='email_body'),
    url(r'^api/loan/email/dates/configure/$', inventory.api.APILoanEmailConfigureDates.as_view(), name='email_send_dates'),
    url(r'^api/loan/email/dates/delete/$', inventory.api.APILoanEmailClearDates.as_view(), name='loan_email_delete_dates'),
    url(r'^api/loan/backfill/$', inventory.api.APIBackfillList.as_view(), name='api_backfill_list'),
    url(r'^api/loan/backfill/create/(?P<pk>[\w\-\ ]+)/$', inventory.api.APILoanBackfillPost.as_view(), name='backfill_create'),
    url(r'^api/loan/backfill/approve/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIApproveBackfill.as_view(), name='backfill_approve'),
    url(r'^api/loan/backfill/deny/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIDenyBackfill.as_view(), name='backfill_deny'),
    url(r'^api/loan/backfill/complete/(?P<pk>[\w\-\ ]+)/$', inventory.api.APICompleteBackfill.as_view(), name='backfill_complete'),
    url(r'^api/loan/backfill/fail/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIFailBackfill.as_view(), name='backfill_fail'),
    url(r'^api/loan/backfill/complete/asset/(?P<pk>[\w\-\ ]+)/$', inventory.api.APICompleteBackfillWithAssets.as_view(), name='backfill_complete_asset'),
    url(r'^api/loan/backfill/notes/(?P<pk>[\w\-\ ]+)/$', inventory.api.APIBackfillNotes.as_view(), name='backfill_notes'),
    url(r'^api/to_asset/(?P<pk>[\w\-\ ]+)/$',inventory.api.APIItemToAsset.as_view(),name='item_to_asset'),
    url(r'^api/to_item/(?P<pk>[\w\-\ ]+)/$',inventory.api.APIAssetToItem.as_view(),name='asset_to_item'),
    url(r'^api/v1/(?P<cls_name>[\w-]+)/$',inventory.api.MyAPI.as_view(),name='api'),
    url(r'^api/below_min_stock/$',inventory.api.APIBelowStock.as_view(), name='below_min_stock'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MeeseeksInc/inventory/forms.py
from django import forms
from .models import Request
from .models import Item
from .models import Tag
from inventory.models import ShoppingCartInstance
 
class RequestForm(forms.ModelForm):
    item_field = forms.ModelChoiceField(queryset=Item.objects.all())
    TYPES = (
        ( 'Dispersal','Dispersal'),
        ('Loan','Loan'),
    )
    type = forms.ChoiceField(label='Select the Request Type', choices=TYPES)
    request_quantity = forms.IntegerField(min_value=1)
    class Meta:
        model = Request
        fields = ('item_field', 'request_quantity','type','reason')
        
class RequestEditForm(forms.ModelForm):
    TYPES = (
        ( 'Dispersal','Dispersal'),
        ('Loan','Loan'),
    )
    type = forms.ChoiceField(label='Select the Request Type', choices=TYPES)
    request_quantity = forms.IntegerField(min_value=1)
    class Meta:
        model = Request
        fields = ('request_quantity','type','reason')

class RequestSpecificForm(forms.Form):  
    quantity = forms.IntegerField(min_value=1)
    TYPES = (
        ( 'Dispersal','Dispersal'),
        ('Loan','Loan'),
    )
    type = forms.ChoiceField(label='Select the Request Type', choices=TYPES)
    reason = forms.CharField(max_length=200)
    def __init__(self, *args, **kwargs):
        super(RequestSpecificForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['quantity','type','reason']
      
class AddToCartForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(AddToCartForm, self).__init__(*args, **kwargs)
        self.fields['quantity'] = forms.IntegerField(required=True, min_value=1)
        TYPES = (
        ( 'Dispersal','Dispersal'),
        ('Loan','Loan'),
        )
        self.fields['type'] = forms.ChoiceField(label='Select the Request Type', choices=TYPES)
        self.fields['reason'] = forms.CharField(max_length=200) 
    fields =('quantity', 'type','reason')

class EditCartAndAddRequestForm(forms.ModelForm):
    quantity = forms.IntegerField(required=True, min_value=1)
    reason = forms.CharField(required=True)
    class Meta:
        model = ShoppingCartInstance
        fields = ('quantity','type','reason')
        

MeeseeksInc/inventory/templates/inventory/add_tags.html
{% extends 'custom_admin/base.html' %} 
{#put this at the top so that the base template is "base.html"#}

{% block content %}

 <h2>Create, Add, and Edit Tags</h2>
 <form method="POST" class="post-form">{% csrf_token %}
 		{{form.create_new_tags.label}}:{{form.create_new_tags}}
 		<br/>
 		(Enter a comma separated list to create multiple new tags.)
 		<br/>
 		<br/>
 		{{form.tag_field.label}}
 		<br/>
 		Choose already existing tags to add to this item.
 		<br/>
 		{{form.tag_field}}
 		<br/>
 		 (Hold shift to select multiple tags.)
 		<br/>
 		<br/>
 	{% for field in form %}
 		{% if field.label != "Create new tags" and field.label != "Add new tags..."%}
    	{{field.label}}:{{ field }}
    	<br/>
    	<br/>
    	{% endif %}
	{% endfor %}
	<button type="submit" onclick="return confirm('Confirm changes?')" class="save btn btn-default">Save</button>
</form>
 	
{% endblock %}

MeeseeksInc/inventory/templates/inventory/base.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/img/Pratt_Logo.ico">

    <title>Meeseeks Inventory</title>

    <!-- Bootstrap core CSS -->
{#    <link href="/static/css/bootstrap.min.css" rel="stylesheet">#}

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/jumbotron.css" rel="stylesheet">
   	<!-- Owen's styles for this template -->
    <link href="/static/css/custom.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
		

	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
	<link rel="stylesheet" href="//cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
	<script type="text/javascript" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<link href={% static 'css/select2.min.css' %} rel="stylesheet" />
	<script src={% static 'js/select2.min.js' %}></script>
	<script src={% static 'js/jquery.csv.min.js' %}></script>
	<script src={% static 'js/jquery.cookie.js' %}></script>
	{% if user.is_superuser %}
		<script src={% static 'js/dataTables.buttons.min.js' %}></script>
	{% endif %}
	<script src={% static 'js/dataTables.select.min.js' %}></script>
	<script src={% static 'js/dataTables.keyTable.min.js' %}></script>
	<script src={% static 'js/dataTables.editor.min.js' %}></script>
	<script src={% static 'js/dataTables.responsive.min.js' %}></script>
	<link rel="stylesheet" href={% static 'css/buttons.dataTables.min.css' %}>
	<link rel="stylesheet" href={% static 'css/select.dataTables.min.css' %}>
	<link rel="stylesheet" href={% static 'css/keyTable.dataTables.min.css' %}>
	<link rel="stylesheet" href={% static 'css/editor.dataTables.min.css' %}>
	<link rel="stylesheet" href={% static 'css/responsive.dataTables.min.css' %}>
	<link rel="stylesheet" href={% static 'css/inlineEdit.css' %}>
{#	<link rel="stylesheet" href={% static 'css/navbar-fixed-side.css' %}>#}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          	{% if user.is_staff %}
          		<a class="navbar-brand" href="{% url 'custom_admin:index' %}">Duke University ECE Department Inventory</a>
        	{% else %}
        		<a class="navbar-brand" href="{% url 'inventory:index' %}">Duke University ECE Department Inventory</a>
        	{% endif %}
          
        </div>
	  {% if user.is_authenticated %}
	      <ul class="nav navbar-nav navbar-right">
	      	<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">API<span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="{% url 'inventory:api_token' %}"> Get Access Token </a></li>
	            <li><a href="{% url 'inventory:api_guide' %}"> API Guide </a></li>
	          </ul>
	        </li>
	      	<li>
		      	<a href="{% url 'inventory:inventory_cart' %}" class="btn btn-default">
		          <span class="glyphicon glyphicon-shopping-cart"></span>
		        </a>
	        </li>
{#	      	<li><a href="{% url 'inventory:search_setup' %}"> Search Parameters </a></li>#}
	        <li><a href="{% url 'logout' %}?next=/">Log out, {{user.username}}</a></li>
	        
	        
	      </ul>
      {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
    {% if messages %}
    	<div class='row'>
    		<div class='col-sm-6 col-sm-offset-3'>
    			{% for message in messages %}
   					 <p{% if message.tags == "success" %} class = "alert alert-success" role="alert" {% elif message.tags == "error" %} class = "alert alert-danger" role="alert" {% endif %}>{{ message }}</p>
   				{% endfor %}
    		</div>
    	</div>
    {% endif %}	
    	
      <!-- Example row of columns -->
      <div class="row">
{#      	<div class="col-sm-6">#}
         	{% block content %}
        	{% endblock %}
{#        </div>#}
      </div>

      <hr>

      <footer>
      	<h2>Our team</h2>
          <p>Owen Chung , Bruna Liborio, Kei Yoshikoshi, and Nick Groszewski </p>
          <p><a class="btn btn-default" href="//github.com/keikumata/Meeseeks-Inc." role="button">Git Repo &raquo;</a></p>
        <p>&copy; 2017 Meeseeks, Inc.</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
{#    <script src=static/js/jquery.min.js"></script>#}
{#    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>#}
{#    <script src="static/js/bootstrap.min.js"></script>#}
{#    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->#}
{#    <script src="static/js/ie10-viewport-bug-workaround.js"></script>#}
  </body>
</html>

MeeseeksInc/inventory/templates/inventory/filter_result.html
{% extends 'inventory/index.html' %}

{% block item_filter_table%}

			<tbody>
            	{% for item in search_list %}
					<tr>
						<td><a href="{% url 'inventory:detail' item.item_id %}">{{ item.item_name }}</a></td>
						<td>{{ item.quantity }}</td>
						<td>{{ item.location }}</td>
						<td>{{ item.model_number }}</td>
						<td>{{ item.description }}</td>
					</tr>
				{% endfor %}
        	</tbody>	
    
{% endblock %}

MeeseeksInc/inventory/templates/inventory/request_edit.html
{% extends 'inventory/index.html' %} 

{% block requestEdit %}
{% include 'inventory/request_edit_inner.html' %}
{% endblock requestEdit %}